version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rentify-app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017
      - DB_NAME=rentify
      - JWT_SECRET=change-me
      - LOG_LEVEL=debug
      - REDIS_URL=redis://redis:6379
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis
    command: sh -c "npm install; npm run dev"

  mongo:
    image: mongo:6
    container_name: rentify-mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=rentify
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    container_name: rentify-redis
    command: ["redis-server", "--save", "20", "1", "--loglevel", "warning"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
